name: Cancel

on: [push]

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.4.0
        with:
          # Ids to cancel core
          # https://api.github.com/repos/devitocodes/devitoboundary/actions/workflows
          workflow_id: [2468423, 14634840]
          access_token: ${{ github.token }}
